# kubectl create secret tls postfix-tls --key [key-file] --cert [cert-file] --namespace postfix

# namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: postfix

# postfix-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: postfix
data:
  master.cf: |
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (no)    (never) (100)
    # ==========================================================================

    smtp      inet  n       -       n       -       -       smtpd
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       bounce
    trace     unix  -       -       n       -       0       bounce
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
        -o syslog_name=postfix/$service_name
    showq     unix  n       -       n       -       -       showq
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache

    # log to stdout
    postlog   unix-dgram n  -       n       -       1       postlogd

    # smtp over tls
    smtps inet n - y - - smtpd
      -o syslog_name=postfix/smtps
      -o smtpd_tls_wrappermode=yes
      -o smtpd_sasl_auth_enable=yes

  main.cf: |
    mynetworks = [MYNETWORKS IN CIDR, separated by ,]

    compatibility_level = 2

    queue_directory = /var/spool/postfix
    command_directory = /usr/sbin
    daemon_directory = /usr/libexec/postfix
    data_directory = /var/lib/postfix
    mail_owner = postfix

    myhostname = [MYHOSTNAME]
    mydomain = [MYDOMAIN]
    myorigin = $mydomain
    mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
    unknown_local_recipient_reject_code = 550

    inet_protocols = ipv4
    inet_interfaces = all

    mailbox_size_limit = 0
    recipient_delimiter = +

    sendmail_path = /usr/sbin/sendmail
    newaliases_path = /usr/bin/newaliases
    mailq_path = /usr/bin/mailq

    setgid_group = postdrop
    html_directory = no
    readme_directory = no

    biff = no
    append_dot_mydomain = no

    meta_directory = /etc/postfix
    shlib_directory = /usr/lib/postfix

    alias_maps = hash:/etc/postfix/aliases
    alias_database = hash:/etc/postfix/aliases

    # relay-restriction
    # smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
    smtpd_relay_restrictions = permit_mynetworks, reject

    # banner
    smtpd_banner = $myhostname ESMTP $mail_name ($mail_version)

    # stdout
    maillog_file = /dev/stdout

    # TLS parameters
    smtpd_tls_cert_file=/etc/ssl/tls.crt
    smtpd_tls_key_file=/etc/ssl/tls.key
    smtpd_use_tls=yes
    smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# postfix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      volumes:
        - name: postfix-config
          configMap:
            name: postfix-config
        - name: postfix-tls
          secret:
            secretName: postfix-tls
      containers:
        - name: postfix
          image: chhsiao1981/docker-postfix
          ports:
            - containerPort: 25
              protocol: TCP
            - containerPort: 465
              protocol: TCP
            - containerPort: 587
              protocol: TCP
          volumeMounts:
            - name: postfix-config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: postfix-config
              mountPath: /etc/postfix/master.cf
              subPath: master.cf
            - name: le-tls
              mountPath: /etc/ssl

# postfix-network
---
apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: postfix
spec:
  selector:
    app: postfix
  ports:
  - protocol: TCP
    port: 25
    targetPort: 25
    name: smtp
  - protocol: TCP
    port: 465
    targetPort: 465
    name: smtps
  - protocol: TCP
    port: 587
    targetPort: 587
    name: sasl
