# kubectl create secret tls postfix-tls --key [key-file] --cert [cert-file] --namespace postfix

# namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: postfix

# postfix-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: postfix
data:
  master.cf: |
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (no)    (never) (100)
    # ==========================================================================

    smtp      inet  n       -       n       -       -       smtpd
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       bounce
    trace     unix  -       -       n       -       0       bounce
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
        -o syslog_name=postfix/$service_name
    showq     unix  n       -       n       -       -       showq
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache

    # log to stdout
    postlog   unix-dgram n  -       n       -       1       postlogd

    # smtp over tls
    smtps inet n - y - - smtpd
      -o syslog_name=postfix/smtps
      -o smtpd_tls_wrappermode=yes
      -o smtpd_sasl_auth_enable=yes

  main.cf: |
    # See /usr/share/postfix/main.cf.dist for a commented, more complete version


    # Debian specific:  Specifying a file name will cause the first
    # line of that file to be used as the name.  The Debian default
    # is /etc/mailname.
    #myorigin = /etc/mailname

    smtpd_banner = $myhostname ESMTP $mail_name (Debian/GNU)
    biff = no

    # appending .domain is the MUA's job.
    append_dot_mydomain = no

    # Uncomment the next line to generate "delayed mail" warnings
    #delay_warning_time = 4h

    readme_directory = no

    # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 3.6 on
    # fresh installs.
    compatibility_level = 3.6



    # TLS parameters
    smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
    smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    smtpd_tls_security_level=may

    smtp_tls_CApath=/etc/ssl/certs
    smtp_tls_security_level=may
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache


    smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
    myhostname = localhost
    alias_maps = hash:/etc/aliases
    alias_database = hash:/etc/aliases
    mydestination = $myhostname, /etc/mailname, localhost, localhost.localdomain, localhost
    relayhost =
    mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    mailbox_size_limit = 0
    recipient_delimiter = +
    inet_interfaces = all
    inet_protocols = all

    # stdout
    maillog_file = /dev/stdout

# postfix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      volumes:
        - name: postfix-config
          configMap:
            name: postfix-config
        - name: postfix-tls
          secret:
            secretName: postfix-tls
      containers:
        - name: postfix
          image: chhsiao1981/docker-postfix
          ports:
            - containerPort: 25
              protocol: TCP
            - containerPort: 465
              protocol: TCP
            - containerPort: 587
              protocol: TCP
          volumeMounts:
            - name: postfix-config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: postfix-config
              mountPath: /etc/postfix/master.cf
              subPath: master.cf
            - name: le-tls
              mountPath: /etc/ssl

# postfix-network
---
apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: postfix
spec:
  selector:
    app: postfix
  ports:
  - protocol: TCP
    port: 25
    targetPort: 25
    name: smtp
  - protocol: TCP
    port: 465
    targetPort: 465
    name: smtps
  - protocol: TCP
    port: 587
    targetPort: 587
    name: sasl
